### ISSUE TITLE
Font Could not load

### ISSUE THREAD

**Issue by sachinmanjule** [javadev/jasper-xml-to-pdf-generator#1]
net.sf.jasperreports.engine.JRRuntimeException: Could not load the following font : 
pdfFontName   : akshar.ttf
pdfEncoding   : Cp1252
isPdfEmbedded : false

**Comment by javadev** [comment]
You may copy font to the fonts folder, add link to the file /src/main/resources/myfamily.xml and rebuild xonverter. :)

**Comment by sachinmanjule** [comment]
ya, i have already done with this.

**Comment by sachinmanjule** [comment]
sorry, i done in other way, thanks

**Comment by A-f4-Avinash** [comment]
how you do ? tell me ...!
